import React, { useMemo, useState } from 'react';
import type { KitLocale } from '../kit/contracts.js';
import { BarChart, BulletChart, Button, DataTable, DonutChart, MetricCard, SeriesChart, StatePanel } from '../kit/index.js';
import { formatMetricValue, targetResult } from '../kit/core/metrics.js';
import { buildDashboard, INITIAL_RANGE, metricHistories } from './dashboard-data.js';
import type { DashboardMeta, DashboardModel, DateRange } from './dashboard-data.js';

export function DashboardPreview({model,meta,locale,onRangeChange,onInspect}:{model:DashboardModel;meta:DashboardMeta;locale:KitLocale;onRangeChange:(range:DateRange)=>void;onInspect:(tab:'options'|'data')=>void}) {
  const ko=locale==='ko', t=(en:string,kr:string)=>ko?kr:en;
  const [chartStyle,setChartStyle]=useState<'area'|'line'>('area');
  const [showComparison,setShowComparison]=useState(true);
  const histories=useMemo(()=>metricHistories(model,locale),[model,locale]);
  const previous=useMemo(()=>model.previousAvailable&&model.previousRange?buildDashboard(model.kind,model.previousRange,locale):null,[model,locale]);
  const total=model.categories.reduce((sum,p)=>sum+(p.value??0),0);
  const leading=[...model.categories].sort((a,b)=>(b.value??0)-(a.value??0))[0];
  const leadingShare=leading&&total>0?new Intl.NumberFormat(locale,{style:'percent',maximumFractionDigits:1}).format((leading.value??0)/total):'—';
  const controlMetric=model.kind==='revenue'?model.metrics[3]:model.metrics[1];
  const target=controlMetric?targetResult(controlMetric):null;
  const current=controlMetric?.current.value??null;
  const format=(value:number|null)=>controlMetric?formatMetricValue(value,controlMetric.definition.unit,locale):'—';
  const sum=(key:string)=>model.rows.reduce((a,r)=>a+(r.values[key]??0),0);
  const split=model.kind==='revenue'?[{key:'net',label:t('Net sales','순매출'),value:sum('netSalesCents')},{key:'refunds',label:t('Refunds','환불액'),value:sum('refundsCents')}]
    :model.kind==='customers'?[{key:'activated',label:t('Activated on signup day','가입 당일 활성화'),value:sum('activated')},{key:'not-activated',label:t('Not activated on signup day','가입 당일 미활성화'),value:sum('signups')-sum('activated')}]
    :[{key:'completed',label:t('Completed','성공'),value:sum('completed')},{key:'failed',label:t('Failed','실패'),value:sum('failed')}];
  const title=model.kind==='revenue'?t('Revenue overview','매출 분석'):model.kind==='customers'?t('Customer overview','고객 분석'):t('Operations overview','운영 분석');
  return <>
    <section className="demo-dashboard-head"><div><div className="demo-eyebrow"><span className="demo-heading-marker"/>{t('ANALYTICS WORKSPACE','분석 워크스페이스')}<span>/ 0{['revenue','customers','operations'].indexOf(model.kind)+1}</span></div><h1>{title}</h1><p>{meta.question}</p></div><div className="demo-dashboard-actions"><span className="demo-sample"><i/>{t('Synthetic data','합성 데이터')}</span><Button onClick={()=>onInspect('data')}>{t('Explore data','데이터 살펴보기')} ↗</Button></div></section>
    <div className="demo-scope-bar"><button className="demo-date-button" onClick={()=>onInspect('options')}><svg viewBox="0 0 20 20" width="15" height="15" fill="none" stroke="currentColor" aria-hidden="true"><rect x="3" y="4" width="14" height="13" rx="2"/><path d="M6 2v5M14 2v5M3 9h14"/></svg>{model.range.start} <span>—</span> {model.range.end}<span>⌄</span></button><span className="demo-comparison-caption"><i/>{model.previousAvailable&&model.previousRange?`${t('vs','비교')} ${model.previousRange.start} — ${model.previousRange.end}`:t('Previous period unavailable','이전 기간 비교 불가')}</span><div className="demo-scope-presets"><button aria-pressed={model.range.start===INITIAL_RANGE.start&&model.range.end===INITIAL_RANGE.end} onClick={()=>onRangeChange(INITIAL_RANGE)}>{t('7 days','7일')}</button><button aria-pressed={model.range.start==='2026-09-01'&&model.range.end==='2026-09-14'} onClick={()=>onRangeChange({start:'2026-09-01',end:'2026-09-14'})}>{t('14 days','14일')}</button></div><span className="demo-utc">UTC</span></div>
    {model.status!=='ready'?<StatePanel kind={model.status==='invalid'?'error':'empty'} title={model.status==='invalid'?t('Check the date range','기간을 확인하세요'):t('No observations in this period','이 기간에 관측값이 없습니다')} message={model.message} action={<Button onClick={()=>onRangeChange(INITIAL_RANGE)}>{t('Reset to sample week','샘플 주간으로 재설정')}</Button>}/>:<>
      {(model.coverage!=='complete'||!model.previousAvailable)&&<StatePanel kind="partial" title={t('Coverage note','데이터 범위 안내')} message={model.message}/>}
      <section className="demo-kpi-ribbon" aria-label={t('Key metrics','핵심 지표')}>{model.metrics.map((metric,i)=><div className="demo-kpi-cell" data-primary={i===0?'true':undefined} style={{'--demo-order':i} as React.CSSProperties} key={metric.definition.id}><MetricCard metric={metric} pattern="comparison" trend={histories[metric.definition.id]} trendPlacement="inline" locale={locale}/></div>)}</section>
      <section className="demo-analysis-grid">
        <div className="demo-primary-chart"><SeriesChart title={model.trendTitle} description={t('Daily performance, with the context behind every point.','일별 흐름과 각 관측값의 맥락을 함께 확인하세요.')} points={model.trend} comparisonPoints={showComparison?previous?.trend:undefined} seriesLabel={t('Current period','현재 기간')} comparisonLabel={t('Previous period','이전 기간')} interactive density="compact" headerActions={<div className="demo-chart-tools"><div className="demo-chart-style" role="group" aria-label={t('Chart presentation','차트 표현')}><button aria-pressed={chartStyle==='area'} onClick={()=>setChartStyle('area')}>{t('Area','영역')}</button><button aria-pressed={chartStyle==='line'} onClick={()=>setChartStyle('line')}>{t('Line','선')}</button></div><button className="demo-compare-toggle" aria-pressed={showComparison&&!!previous} disabled={!previous} title={!previous?t('Complete previous-period observations are required.','완전한 이전 기간 관측값이 필요합니다.'):undefined} onClick={()=>setShowComparison(!showComparison)}><span aria-hidden="true">↔</span>{t('Compare','비교')}</button></div>} maxHeight={216} area={chartStyle==='area'} unit={{kind:'number',label:model.trendUnit}} yAxisLabel={model.trendUnit} xAxisLabel={t('Date · UTC','날짜 · UTC')} locale={locale}/><div className="demo-chart-readout"><span><i/>{t('Period total','기간 합계')} <strong>{model.metrics[0]&&formatMetricValue(model.metrics[0].current.value,model.metrics[0].definition.unit,locale)}</strong></span><span>{t('Previous','이전')} <strong>{model.metrics[0]?.previous?formatMetricValue(model.metrics[0].previous.value,model.metrics[0].definition.unit,locale):t('Unavailable','비교 불가')}</strong></span><button onClick={()=>onInspect('data')}>{t('Source records','원천 기록')} →</button></div></div>
        <div className="demo-companion-stack"><div className="demo-breakdown"><BarChart title={model.categoriesTitle} points={model.categories} unit={{kind:'number',label:model.categoriesUnit}} locale={locale}/><p className="demo-channel-insight"><span>{t('TOP CONTRIBUTOR','최대 기여 채널')}</span><strong>{leading?.label??'—'} <b>{leadingShare}</b></strong></p></div><div className="demo-control-card" data-verdict={target?.met===null?'unknown':target?.met?'met':'missed'}><div className="demo-control-eyebrow"><span>{t('TARGET MONITOR','목표 모니터')}</span><span>{t('Period ratio','기간 비율')}</span></div><div><span className="demo-control-icon" aria-hidden="true">{target?.met?'✓':'!'}</span><strong>{controlMetric?.definition.title}</strong><span className="demo-verdict">{target?.met===null?t('Not assessed','판단 보류'):target?.met?t('Within target','목표 충족'):t('Watch','주의')}</span></div><div className="demo-control-values"><strong>{format(current)}</strong><span>{t('Target','목표')} {controlMetric?.definition.target?.relation==='at-most'?'≤':'≥'} {format(controlMetric?.definition.target?.value??null)}</span></div>{controlMetric?.definition.target&&current!==null&&<BulletChart title={t('Target comparison','목표 비교')} actual={current} target={controlMetric.definition.target.value} unit={controlMetric.definition.unit} locale={locale} showDataTable={false}/>}</div></div>
      </section>
      <section className="demo-evidence-grid"><DataTable key={`${model.kind}:${model.range.start}:${model.range.end}`} title={model.tableTitle} rows={model.rows} columns={model.columns} getRowId={r=>r.id} pageSize={4} selectable locale={locale}/><div className="demo-outcome-panel"><DonutChart title={model.kind==='revenue'?t('Gross sales composition','총매출 구성'):model.kind==='customers'?t('Same-day activation mix','가입 당일 활성화 구성'):t('Attempt outcomes','작업 시도 결과')} points={split} unit={model.kind==='revenue'?{kind:'money',currency:'USD',exponent:2}:{kind:'count'}} locale={locale}/><div className="demo-data-health"><span><i/>{t('Coverage','데이터 범위')} <strong>{model.coverage==='complete'?t('Complete','완전'):t('Partial','일부')}</strong></span><span>{new Intl.NumberFormat(locale).format(model.rows.length)} {t('source rows','개 원천 행')}</span><button onClick={()=>onInspect('data')}>{t('Inspect','자세히')} ↗</button></div></div></section>
    </>}
    <p className="demo-canvas-footnote"><span>{t('Synthetic dataset · no live connection','합성 데이터 · 실시간 연결 없음')}</span><span>{t('One scope. Every number connected.','하나의 기간, 함께 연결되는 모든 숫자.')}</span></p>
  </>;
}
